[toolchain]

[features]
seeds = true
skip-lint = true
skip-idl = true

[programs.devnet]
crowdfunding = "CYunzofmkHK7gVcchq7JsvdtkMNkKy9W7pN3VkbzUBuY"

[programs.localnet]
crowdfunding = "CYunzofmkHK7gVcchq7JsvdtkMNkKy9W7pN3VkbzUBuY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
